stages:
  - lint
  - test
language: node_js
node_js:
  - stable
addons:
  apt:
    packages:
      - libnotify-bin
install: npm ci --ignore-scripts
before_script: npm install -g npm@5.8.0
before_install: |
  [[ ! -x ~/npm/node_modules/.bin/npm ]] && {
    cd ~/npm && npm install npm
    cd -
  } || true
  export PATH=~/npm/node_modules/.bin:$PATH
cache:
  directories:
    - '~/.npm'
    - '~/npm'
jobs:
  include:
    - stage: test
      install: &1
        - npm install
      script: npm run test:coverage
      before_install: true
      cache: &2
        directories:
          - '~/.npm'
          - node_modules
    - stage: test
      install: *1
      script: npm run test
      before_install: true
      after_success: npm run test:coverage
      cache: *2
      node_js: '8'
      if: branch != master
    - stage: test
      install: *1
      script: npm run test:coverage
      before_install: true
      cache: *2
      node_js: '10'
      if: branch != master
    - stage: lint
      script: npm run lint
      before_install: true
      install:
        - npm install
after_success: npm run test:coverage
sudo: false
before_deploy:
  - rm -rf node_modules
