stages:
  - lint
  - test
language: node_js
node_js:
  - stable
addons:
  apt:
    packages:
      - libnotify-bin
before_script: yarn upgrade react-scripts@latest
jobs:
  include:
    - stage: test
      install: *1
      script: yarn test:coverage
      before_install: true
      cache: *2
      node_js: '10'
      if: branch != master
    - stage: lint
      script: yarn lint
      before_install: true
      install:
        - yarn install
sudo: false
before_deploy:
  - rm -rf node_modules
