stages:
  # - lint
  - test
language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
before_script: 
  - npm install --save --save-exact react-scripts@3.2.0

addons:
  apt:
    packages:
      - libnotify-bin
jobs:
  include:
    - stage: test
      install: *1
      script: yarn test:coverage
      before_install: true
      # cache: *2
      # node_js: '10'
      # if: branch != master
    - stage: lint
      script: yarn lint
      before_install: true

sudo: false
after_success:
  - yarn report
before_deploy:
  - rm -rf node_modules
