stages:
  # - lint
  - test
language: node_js
before_script: 
  - npm install -g codecov
node_js:
  - 8
cache:
  directories:
    - node_modules

addons:
  apt:
    packages:
      - libnotify-bin
jobs:
  include:
    - stage: test
      install: *1
      script: yarn test:coverage
      before_install: true
    - stage: lint
      script: yarn lint

sudo: true
after_success:
  - yarn report
before_deploy:
  - rm -rf node_modules
