version: 2.1 # use CircleCI 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout # special step to check out source code to working directory

      - run:
          name: Install dependencies with NPM
          command: npm install # replace with `yarn install` if using yarn

      - run:
          name: Check if yarn lint was run
          command: npm run lint

      - run:
          name: Run tests
          # Runs jest with "--maxWorkers=2" argument to avoid OOM issues
          command: npm run test:coverage # replace with `yarn test` if using yarn

      - run:
          name: Coverage
          command: npm run report

workflows:
  version: 2.1
  Build and Test:
    jobs:
      - build
